on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Prereqs
        run: |
          sudo apt-get update
          docker login -u belkonar -p ${{secrets.DOCKER}}
          docker buildx create --driver cloud belkonar/whynot
          docker buildx build --platform linux/arm64 . --builder cloud-belkonar-whynot --tag belkonar/mysite:${{github.event.release.tag_name}} --push
