on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Prereqs
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libssl-dev xz-utils liblz4-tool musl-tools
          sudo apt-get install -y gcc-aarch64-linux-gnu
          rustup update
          rustup target add aarch64-unknown-linux-gnu
      - run: |
          cargo build --target=aarch64-unknown-linux-gnu --release
          zip -r aarch-linux.zip target/aarch64-unknown-linux-gnu/release/blag -j
